# Generated by Django 6.0.4 on 2026-04-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoMon',
            fields=[
                ('ma_bm', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_bm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DonViTaiTro',
            fields=[
                ('ma_dvtt', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_dvtt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ma_khoa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_khoa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('ma_gv', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_gv', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('bo_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giangvien', to='core.bomon')),
            ],
        ),
        migrations.CreateModel(
            name='DeTai',
            fields=[
                ('ma_dt', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_dt', models.CharField(max_length=200)),
                ('trang_thai', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('gv_huong_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detai', to='core.giangvien')),
            ],
        ),
        migrations.AddField(
            model_name='bomon',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomon', to='core.khoa'),
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('ma_sv', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_sv', models.CharField(max_length=200)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhvien', to='core.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='TaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ngay_dang_ky', models.DateField()),
                ('ngay_duyet', models.DateField(blank=True, null=True)),
                ('de_tai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taitro', to='core.detai')),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donvitaitro')),
            ],
        ),
        migrations.CreateModel(
            name='ThamGiaDeTai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(default='member', max_length=100)),
                ('de_tai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detai')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sinhvien')),
            ],
            options={
                'unique_together': {('de_tai', 'sinh_vien')},
            },
        ),
    ]
