# Generated by Django 6.0.4 on 2026-04-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detai',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donvitaitro',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khoa',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taitro',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thamgiadetai',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thamgiadetai',
            name='vai_tro',
            field=models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='HuongDanDeTai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('vai_tro', models.CharField(choices=[('main', 'chính'), ('member', 'phụ')], max_length=20)),
                ('de_tai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detai')),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giangvien')),
            ],
            options={
                'unique_together': {('de_tai', 'giang_vien')},
            },
        ),
    ]
